[changelog]
header = "## Changelog\n\n"
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}

{% for commit in commits %}
- {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/your-org/your-repo/commit/{{ commit.id }}))
{% endfor %}
{% endfor %}
"""
footer = ""

[git]
conventional_commits = true
filter_unconventional = false

[commit_types]
feat = "Features"
fix = "Fixes"
chore = "Chores"
refactor = "Refactoring"
docs = "Documentation"
test = "Tests"
ci = "CI/CD"