name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  create_github_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Notes
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: gh release create ${{ github.ref }} --title "${{ steps.changelog.outputs.tag }}" --notes "${{ steps.changelog.outputs.clean_changelog }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
