name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  create_github_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release Notes
        run: |
          DATE=$(date + "%B %d, %Y")
          gh release create ${{ github.ref_name}} \
          --title "${{ github.ref_name}} $DATE" \
          --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
